language: node_js
node_js:
- '8.8.1'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgif-dev

cache:
  directories:
    - node_modules
    - .python
install: npm install

script: npm test
